[package]
name = "guiying-desktop"
version = "0.1.0"
description = "A local-first, evidence-led photo archive deduplication desktop app"
authors = ["siguago"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "guiying_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.7.2"
guiying-core = { version = "0.1.0", path = "../crates/guiying-core" }
tokio = { version = "1.53.1", features = ["sync"] }
uuid = { version = "=1.20.0", default-features = false }
